name: Prettier Check
on:
  pull_request:
  push:
    branches: [main]
jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        id: prettier-run
        with:
          prettier_options: --check **/*.{js,ts,md}
          same_commit: true
