name: Prettier Check
on:
  pull_request:
  push:
    branches: [main]
jobs:
  prettier:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        id: prettier-run
        with:
          only_changed: True
          dry: True

