name: On Merge
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual'
        required: true
        type: boolean
  pull_request:
    types:
      - closed
    branches:
      - main
      
jobs:
  run_if:
    if:  github.event.inputs.tag == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release PR branch ${{ github.event.inputs.tag }}"
