name: On Merge
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main
      
jobs:
  run_if:
    if:  (github.event.pull_request.merged == true && startsWith(github.head_ref, 'release(skyrim-platform)')) || github.event.workflow_dispatch
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release PR branch ${{ github.head_ref }}"
