name: On Merge
on:
  pull_request:
    types:
      - closed
      
jobs:
  run_if:
    if:  github.event.pull_request.merged == true && startsWith(github.head_ref, 'Update SP to')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release PR branch"
