name: On Merge
on:
  workflow_dispatch:
    inputs:
      tags:
        required: false
  pull_request:
    types:
      - closed
    branches:
      - main
      
jobs:
  run_if:
    if:  (github.event.pull_request.merged == true && startsWith(github.head_ref, 'release(skyrim-platform)')) || github.event.inputs
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release stuff"
