name: On Merge
on:
  workflow_dispatch:
    inputs:
      tags:
        required: true
  pull_request:
    types:
      - closed
    branches:
      - main
      
jobs:
  run_if:
    if:  true
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release PR branch ${{ github.event.inputs.tags }}"
