name: On Merge
on:
  pull_request:
    types:
      - [closed]
    branches:
      - 'releases/**'
jobs:
  run_if:
    if:  startsWith(github.head_ref, 'releases/') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "The head of this PR starts with 'releases/'"