name: On Merge
on:
  pull_request:
    types:
      - closed
    branches:    
      - 'release-sp**'
      
jobs:
  run_if:
    if:  github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "Release PR branch"
