# This is a basic workflow to help you get started with Actions

name: SP Release


on:
  workflow_dispatch:

jobs:
  filework:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Generate changelog
        run: |
          oldver='2.3.0'
          newver='2.4.0'
          echo "# SP $newver Release Notes"$'\n'"bla bla bla"$'\n' >> "/output/sp-$newver.md"
          for file in `find "${{github.workspace}}/content/dev" -type f -name "sp*.md"`
          do
            content=$(< $file)
            echo "$content" >> "/output/sp-$newver.md"
            echo $'\n' >> "/output/sp-$newver.md"
          done
          cat "/output/sp-$newver.md"

      - name: Replace version number
        run: |
          oldver='2.3.0'
          newver='2.4.0'
          sed -i "s/$oldver/$newver/g" ${{github.workspace}}/content/replaces/testreaplce.txt

