name: Update SP Types
on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-version]
jobs:
  updatetype:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update files
        run: |
          TARGET="index.d.ts"
          VERSION="2.5.0"
          CONTENT="test content2"
          echo "$CONTENT" > $TARGET
          sed -i "s/\"version\".*,/\"version\": \"$VERSION\",/g" package.json
          echo "finish update data"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: Update Workflow
          message: 'update types to ${{ env.VERSION }}'
