name: Update SP Types
on:
  repository_dispatch:
    types: [update-types]
jobs:
  updateType:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update files
        run: |
          CONTENT="test content2"
          echo "$CONTENT" > index.d.ts
          sed -i "s/\"version\".*,/\"version\": \"${{ github.event.client_payload.version }}\",/g" package.json
          echo "finish update data"

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: Update Workflow
          message: 'update types to ${{ github.event.client_payload.version }}'
