name: Update Trigger
on:
  workflow_dispatch:
jobs:
  sprelease:
    runs-on: ubuntu-latest

    steps:
      - name: Update Types Repo
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: shevernitskiy/actionsand
          event-type: update-types
          client-payload: '{"version": "2.6.0"}'